GET http://localhost:8080/create?orderNo=123
Accept: application/json

###


POST http://localhost:8080/discount
Content-Type: application/json

{
  "id": "17208",
  "orderNo": "C1720817208",
  "discount": {
    "discountAmount": 100,
    "num": 10
  }
}

###


POST http://localhost:8080/fireSend
Content-Type: application/json

{
  "id": "17208",
  "orderNo": "C1720817208",
  "discount": {
    "discountAmount": 100,
    "num": 10
  }
}

###